"""CLIP runtime — lazy-loaded, CPU/CUDA autodetect.

Only imported by the vision pipeline. The base FastAPI app does not depend on
torch — install the `[ml]` extras (`pip install -e ".[dev,ml]"`) before using
the upload pipeline or semantic search.
"""

from __future__ import annotations

import logging
import os
from functools import lru_cache
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import torch as _torch_t  # noqa: F401


def _detect_inference_backend() -> dict:
    """Pick the best torch device for inference. Returns a dict with
    `device` (torch device string), `backend` (human label), `fallback`
    (bool — True when we landed on CPU because nothing better was
    reachable from this process).

    Probe order:
      1. CUDA (NVIDIA, torch.cuda)
      2. MPS  (Apple Silicon, torch.backends.mps)
      3. XPU  (Intel iGPU/Arc, via Intel Extension for PyTorch)
      4. CPU  (fallback)

    Intel NPU and OpenVINO-served devices aren't a torch.device — they
    need a separate inference path (model conversion to OpenVINO IR
    + Core.compile_model). The worker reports them in heartbeat
    metadata for the dashboard but doesn't dispatch torch loads to
    them. Wiring that path is a separate workstream (todo §F1/F2
    quantization + model conversion).
    """
    try:
        import torch
    except ImportError:
        return {"device": "cpu", "backend": "cpu", "fallback": True,
                "reason": "torch not installed"}
    # 1. CUDA
    try:
        if torch.cuda.is_available():
            return {"device": "cuda", "backend": "torch.cuda", "fallback": False,
                    "device_name": torch.cuda.get_device_name(0)}
    except Exception:
        pass
    # 2. MPS (Apple Silicon)
    try:
        mps = getattr(torch.backends, "mps", None)
        if mps is not None and mps.is_available() and mps.is_built():
            return {"device": "mps", "backend": "torch.mps", "fallback": False,
                    "device_name": "Apple Silicon GPU"}
    except Exception:
        pass
    # 3. XPU (Intel iGPU via IPEX)
    try:
        if hasattr(torch, "xpu") and torch.xpu.is_available():
            try:
                name = torch.xpu.get_device_name(0)
            except Exception:
                name = "Intel XPU"
            return {"device": "xpu", "backend": "torch.xpu", "fallback": False,
                    "device_name": name}
    except Exception:
        pass
    return {"device": "cpu", "backend": "cpu", "fallback": True,
            "reason": "no GPU/MPS/XPU available"}


def _runtime_toml_path() -> str:
    """Where to cache the probe result. The container's /app is writable
    and the bind-mount means the host sees the file too — handy for
    debugging without `docker exec`."""
    import os as _os
    return _os.environ.get("NEUTHEK_RUNTIME_TOML", "/app/runtime.toml")


def _write_runtime_toml(info: dict) -> None:
    """Persist the chosen backend so subsequent boots can read it
    instead of probing again. Best-effort; failures don't matter."""
    try:
        from datetime import datetime, timezone
        path = _runtime_toml_path()
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("# auto-generated by backend.vision.runtime\n")
            fh.write(f"# probed_at = \"{datetime.now(timezone.utc).isoformat()}\"\n")
            fh.write(f"device = \"{info['device']}\"\n")
            fh.write(f"backend = \"{info['backend']}\"\n")
            fh.write(f"fallback = {str(info.get('fallback', False)).lower()}\n")
            if info.get("device_name"):
                fh.write(f"device_name = \"{info['device_name']}\"\n")
            if info.get("reason"):
                fh.write(f"reason = \"{info['reason']}\"\n")
    except Exception:
        pass


def _device() -> str:
    """Back-compat shim — returns just the torch device string. New
    callers should use `get_runtime_info()` for the full picture."""
    return _detect_inference_backend()["device"]


@lru_cache(maxsize=1)
def get_runtime_info() -> dict:
    """One-shot probe at first call. Result cached for the process
    lifetime + persisted to runtime.toml for next boot's debugging."""
    info = _detect_inference_backend()
    _write_runtime_toml(info)
    return info


@lru_cache(maxsize=1)
def get_device() -> str:
    return get_runtime_info()["device"]


def _report_loaded(model_id: str, device: str) -> None:
    """C8.2 — record that this worker loaded `model_id` on `device`
    in the model_runs table. Best-effort: a failed write never raises
    into the loader so model availability doesn't depend on the DB."""
    try:
        from backend.heartbeats import record_model_state_sync
    except Exception:
        return
    mem: int | None = None
    try:
        import torch
        if device.startswith("cuda") and torch.cuda.is_available():
            mem = int(torch.cuda.memory_allocated())
    except Exception:
        mem = None
    try:
        record_model_state_sync(
            model_id=model_id,
            state="loaded",
            device=device,
            memory_allocated_bytes=mem,
        )
    except Exception:
        pass


def _materialize_to(model, device):
    """Move a transformers/torch model onto `device` safely.

    Modern transformers releases load weights via ``init_empty_weights``
    on the *meta* device when ``low_cpu_mem_usage`` is auto-enabled (it
    is, for several CausalLM and BLIP code paths). Calling ``.to(device)``
    on a still-meta tensor raises:

        NotImplementedError: Cannot copy out of meta tensor; no data!
        Please use torch.nn.Module.to_empty()…

    The fix is a two-step move: ``to_empty`` allocates real storage on
    the target device first, then ``load_state_dict`` (which transformers
    already did internally) repopulates it. In practice, by the time we
    get the model object back from ``from_pretrained`` it has already
    been materialized for us *if* we never touched ``device_map`` or
    ``low_cpu_mem_usage``. Our defense in depth: try the normal ``.to``
    first; on the meta-tensor error, fall back to ``.to_empty`` + a
    fresh state-dict copy from the model itself.
    """
    import torch  # type: ignore
    try:
        return model.to(device)
    except NotImplementedError as e:
        if "meta tensor" not in str(e).lower():
            raise
        # Re-fetch the state dict (these are real tensors because
        # transformers stores them off-meta after load) and re-attach
        # via to_empty + load.
        try:
            sd = {k: v.detach().clone() for k, v in model.state_dict().items()}
            model = model.to_empty(device=device)
            model.load_state_dict(sd, strict=False, assign=True)
            return model
        except Exception:
            # Last-resort: re-load with low_cpu_mem_usage=False so the
            # whole model materializes in CPU RAM, then move it.
            raise


from backend.vision import vram_manager as _vram


def _managed_load(key: str, est_gb: float, evictable: bool, cache_clear) -> None:
    """Register a getter with the VRAM manager and free GPU room before a load.

    Called at the top of each model getter body (which runs only on a cache
    miss = an actual load). Pair with `_vram.mark_resident`/`touch` after load.
    """
    _vram.register(key, est_gb=est_gb, evictable=evictable, cache_clear=cache_clear)
    if get_device() == "cuda":
        _vram.ensure_room(est_gb)


@lru_cache(maxsize=1)
def get_clip():
    """Load OpenCLIP image+text model and tokenizer once.

    Returns (model, preprocess, tokenizer, device).
    First call downloads weights via open_clip; subsequent calls hit the cache.
    """
    import open_clip
    import torch

    from backend.config import settings

    device = get_device()
    _managed_load("clip", 1.75, True, get_clip.cache_clear)
    model, _, preprocess = open_clip.create_model_and_transforms(
        settings.clip_model_name,
        pretrained=settings.clip_pretrained,
    )
    model = _materialize_to(model, device).eval()
    if device == "cuda":
        model = model.half()
    tokenizer = open_clip.get_tokenizer(settings.clip_model_name)

    # Disable autograd permanently for inference.
    for p in model.parameters():
        p.requires_grad_(False)

    _report_loaded("clip", device)
    _vram.mark_resident("clip"); _vram.touch("clip")
    return model, preprocess, tokenizer, device


@lru_cache(maxsize=512)
def encode_text_cached(text: str):
    """Encode a single text prompt and L2-normalise. Cached for repeated queries."""
    import torch

    model, _, tokenizer, device = get_clip()
    with torch.no_grad():
        tokens = tokenizer([text]).to(device)
        feats = model.encode_text(tokens)
        feats = feats / feats.norm(dim=-1, keepdim=True)
    return feats[0].float().cpu().numpy()


@lru_cache(maxsize=1)
def get_doc_summarizer():
    """Load the abstractive document summarizer once (Phase 11).

    DistilBART CNN-12-6 (~300 MB) is trained on CNN/DailyMail and produces
    sentence-level paraphrased summaries — "The report covers Q4 revenue
    growth and Phase 11 release plans" instead of pasting the first three
    sentences verbatim. Runs ~2-4 s on CPU per call.

    Returns (model, tokenizer, device).
    """
    import torch

    # Bypass transformers' top-level lazy loader — when other libs in the
    # process (open_clip, insightface) touch transformers' namespace early,
    # the lazy `_get_module` cache can wedge in a partial state where
    # `from transformers import AutoModelForSeq2SeqLM` raises ImportError
    # even though the symbol is reachable from the submodule. Importing
    # by full path skips the cache.
    from transformers.models.auto.modeling_auto import AutoModelForSeq2SeqLM
    from transformers.models.auto.tokenization_auto import AutoTokenizer

    from backend.config import settings

    device = get_device()
    model_name = getattr(
        settings, "summarizer_model_name", "sshleifer/distilbart-cnn-12-6"
    )
    _managed_load("doc_summarizer", 0.3, True, get_doc_summarizer.cache_clear)

    dtype = torch.float16 if device == "cuda" else torch.float32
    # `low_cpu_mem_usage=False` forces transformers to materialize the
    # whole model in real (non-meta) tensors at load time. Otherwise
    # recent transformers builds enable the meta-tensor fast-load by
    # default for some models, and the subsequent `.to(device)` blows
    # up with NotImplementedError("Cannot copy out of meta tensor").
    model = AutoModelForSeq2SeqLM.from_pretrained(
        model_name, torch_dtype=dtype, low_cpu_mem_usage=False
    )
    model = _materialize_to(model, device).eval()
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    for p in model.parameters():
        p.requires_grad_(False)

    _report_loaded("doc_summarizer", device)
    _vram.mark_resident("doc_summarizer"); _vram.touch("doc_summarizer")
    return model, tokenizer, device


@lru_cache(maxsize=1)
def get_florence2():
    """Load Microsoft Florence-2 once (Phase 11 v2).

    Florence-2 is a multitask vision foundation model. We use two task
    tokens:
      - <MORE_DETAILED_CAPTION>: 2-3 sentence dense scene description.
      - <OCR>: reads visible text in the image (whiteboards, screenshots,
        documents) — replaces a separate easyocr/tesseract dependency.

    First call downloads ~3.4 GB to `${HF_HOME}`. Uses fp16 on CUDA,
    fp32 on CPU (CPU works but is slow ~10-20s per image).

    Returns (model, processor, device).

    Compatibility: Florence-2 ships its own modeling code via
    `trust_remote_code=True`. Newer transformers (4.50+) renamed/removed
    a few attributes the bundled file expects; we patch them defensively
    after load so first inference doesn't AttributeError.
    """
    import torch
    from transformers import AutoModelForCausalLM, AutoProcessor

    from backend.config import settings

    device = get_device()
    model_name = settings.caption_model_name
    _managed_load("florence2", 1.14, False, get_florence2.cache_clear)

    dtype = torch.float16 if device == "cuda" else torch.float32
    # Florence-2's bundled modeling code predates the `_supports_sdpa`
    # / `_supports_flash_attn_2` flags that transformers 4.50+ checks
    # when resolving `attn_implementation`. We force `attn_implementation
    # ="eager"` at load to bypass the resolver entirely; older trust-
    # remote-code paths still accept it.
    #
    # `low_cpu_mem_usage=False` is critical — without it transformers
    # uses the meta-tensor fast-load on Florence-2 and `.to(device)`
    # raises NotImplementedError on every later call. Forcing full
    # materialization at load time avoids the entire class of bug.
    try:
        model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torch_dtype=dtype,
            trust_remote_code=True,
            attn_implementation="eager",
            low_cpu_mem_usage=False,
        )
    except TypeError:
        model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torch_dtype=dtype,
            trust_remote_code=True,
            low_cpu_mem_usage=False,
        )
    model = _materialize_to(model, device).eval()

    # Defensive belt-and-braces patch: set the flags on every level the
    # resolver might check (class + instance + every submodule that
    # inherits PreTrainedModel). A missing attribute on any of those
    # blows up generate() the first time.
    for attr in ("_supports_sdpa", "_supports_flash_attn_2", "_supports_flash_attn"):
        try:
            setattr(type(model), attr, False)
        except Exception:
            pass
        try:
            setattr(model, attr, False)
        except Exception:
            pass
        for module in model.modules():
            try:
                setattr(module, attr, False)
            except Exception:
                pass

    processor = AutoProcessor.from_pretrained(
        model_name, trust_remote_code=True
    )

    for p in model.parameters():
        p.requires_grad_(False)

    _report_loaded("florence2", device)
    _vram.mark_resident("florence2"); _vram.touch("florence2")
    return model, processor, device


@lru_cache(maxsize=1)
def get_trocr():
    """Load Microsoft TrOCR (handwritten) once — the handwriting line
    RECOGNIZER that complements Florence-2's region DETECTION.

    Florence-2 finds WHERE text is (bounding boxes) reliably even on cursive,
    but transcribes handwriting poorly. TrOCR (`microsoft/trocr-base-
    handwritten`, ~330 MB, Apache-2.0) is trained specifically to READ a single
    handwritten text LINE, so the OCR / in-image-translate paths crop each
    Florence region and run it through TrOCR for an accurate read.

    PINNED TO CPU on purpose: the 8 GB GPU is already near-full with Florence-2
    + CLIP + the translator (~6.4/8 GB), so we deliberately do NOT add a
    resident GPU model here. TrOCR runs ~1-3 s per cropped line on CPU, which is
    the accepted trade for actually reading handwriting. The device is FORCED to
    "cpu" regardless of `get_device()` so a CUDA box still keeps its VRAM free.

    First call downloads the weights to ${HF_HOME} (pre-baked in the Dockerfile
    so production never pays it). Returns (model, processor, device="cpu").
    """
    import torch

    # Full-path imports bypass transformers' lazy top-level loader, which can
    # wedge in a partial ImportError state once open_clip / insightface / the
    # Florence loader have touched the transformers namespace (same workaround
    # as get_doc_summarizer / the NLLB loader).
    from transformers.models.trocr.processing_trocr import TrOCRProcessor
    from transformers.models.vision_encoder_decoder.modeling_vision_encoder_decoder import (  # noqa: E501
        VisionEncoderDecoderModel,
    )

    from backend.config import settings

    model_name = getattr(
        settings, "trocr_model_name", "microsoft/trocr-base-handwritten"
    )
    # Sub-project A: TrOCR may now run RESIDENT ON THE GPU — the 12 GB 5070 has
    # the headroom the 8 GB 4060 lacked, and GPU TrOCR is ~10x faster per line.
    # OCR_TROCR_DEVICE = auto|cuda|cpu; `auto` -> cuda when available. Registered
    # evictable, and falls back to CPU on any CUDA load failure so a full card
    # never breaks handwriting OCR (it just runs slower).
    pref = os.environ.get("OCR_TROCR_DEVICE", "auto").strip().lower()
    want_cuda = (pref == "cuda") or (pref == "auto" and get_device() == "cuda")
    device = "cuda" if want_cuda else "cpu"
    try:
        if device == "cuda":
            _vram.register("trocr", est_gb=0.6, evictable=True,
                           cache_clear=get_trocr.cache_clear)
            _vram.ensure_room(0.6)
        dtype = torch.float16 if device == "cuda" else torch.float32
        model = VisionEncoderDecoderModel.from_pretrained(
            model_name, torch_dtype=dtype, low_cpu_mem_usage=False
        )
        model = _materialize_to(model, device).eval()
    except Exception:
        try:
            import logging
            logging.getLogger(__name__).warning(
                "trocr: GPU load failed; CPU fallback", exc_info=True)
        except Exception:
            pass
        device = "cpu"
        model = VisionEncoderDecoderModel.from_pretrained(
            model_name, torch_dtype=torch.float32, low_cpu_mem_usage=False
        )
        model = _materialize_to(model, device).eval()
    processor = TrOCRProcessor.from_pretrained(model_name)

    for p in model.parameters():
        p.requires_grad_(False)

    _report_loaded("trocr", device)
    if device == "cuda":
        _vram.mark_resident("trocr"); _vram.touch("trocr")
    return model, processor, device


@lru_cache(maxsize=1)
def get_lama():
    """LaMa deep-inpainting model — the 'magic eraser' for clean in-image text
    removal + natural background reconstruction (far better than cv2.inpaint on
    textured/photo/gradient backgrounds). Returns a callable `lama(pil_img,
    pil_mask) -> pil_img` (mask: white where to erase), or None when LaMa isn't
    available so the caller falls back to cv2/bg-fill. GPU when present, CPU
    otherwise; registered evictable. The ~200 MB model downloads to $TORCH_HOME
    (mounted at /models) on first use. NEVER raises — any failure → None."""
    try:
        import torch
        from simple_lama_inpainting import SimpleLama

        # Persist the downloaded weights on the mounted model cache.
        os.environ.setdefault("TORCH_HOME", os.environ.get("HF_HOME", "/models"))
        device = "cuda" if (get_device() == "cuda" and torch.cuda.is_available()) else "cpu"
        if device == "cuda":
            _vram.register("lama", est_gb=0.8, evictable=True,
                           cache_clear=get_lama.cache_clear)
            _vram.ensure_room(0.8)
        try:
            lama = SimpleLama(device=torch.device(device))
        except TypeError:
            lama = SimpleLama()  # older signature: auto-device
        if device == "cuda":
            _vram.mark_resident("lama"); _vram.touch("lama")
        _report_loaded("lama", device)
        return lama
    except Exception:
        logging.getLogger(__name__).warning(
            "lama unavailable; in-image erase falls back to cv2/bg-fill",
            exc_info=True,
        )
        return None


@lru_cache(maxsize=1)
def get_caption_model():
    """BLIP fallback for image captioning when Florence-2 fails to load.

    Florence-2 is the primary captioner (`get_florence2`); this exists so
    the pipeline keeps working on transformers minor-version mismatches or
    download failures. Returns (model, processor, device).
    """
    import torch

    # Lazy-loader workaround — see comment in get_doc_summarizer.
    from transformers.models.blip.modeling_blip import (
        BlipForConditionalGeneration,
    )
    from transformers.models.blip.processing_blip import BlipProcessor

    from backend.config import settings

    device = get_device()
    model_name = settings.caption_fallback_model_name
    _managed_load("caption", 0.87, True, get_caption_model.cache_clear)

    dtype = torch.float16 if device == "cuda" else torch.float32
    model = BlipForConditionalGeneration.from_pretrained(
        model_name, torch_dtype=dtype, low_cpu_mem_usage=False
    )
    model = _materialize_to(model, device).eval()
    processor = BlipProcessor.from_pretrained(model_name)

    for p in model.parameters():
        p.requires_grad_(False)

    _report_loaded("caption_fallback", device)
    _vram.mark_resident("caption"); _vram.touch("caption")
    return model, processor, device


@lru_cache(maxsize=1)
def get_summary_rewriter():
    """Small instruction LLM that rewrites raw caption + names + OCR + scene
    into one natural search-friendly sentence (Phase 11 v2).

    Replaces regex-based pronoun fixes with an LLM that handles
    coreference ("a man" → "Mr Koler" → fixes "his cell phone" → "his"
    when third person, "my" when first person) and integrates OCR text
    descriptively ("matrix algebra equations including 2z=-4") rather
    than verbatim copy-paste.

    Qwen2.5-1.5B-Instruct is the cost/quality sweet spot: ~3 GB on disk,
    ~2 GB VRAM in fp16, Apache 2.0. Returns (model, tokenizer, device).
    """
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    from backend.config import settings

    device = get_device()
    model_name = settings.rewriter_model_name

    from backend.vision.quant import rewriter_quant_config
    quant = rewriter_quant_config() if device == "cuda" else None
    if quant is not None:
        # 7B-4bit ~4.5 GB; evictable so it swaps with MADLAD (exotic-lang
        # fallback is rare — MADLAD stays hot for the common case).
        _vram.register("rewriter", est_gb=4.5, evictable=True,
                       cache_clear=get_summary_rewriter.cache_clear)
        _vram.ensure_room(4.5)
        # bnb path: device_map pins to GPU 0; NO low_cpu_mem_usage / post .to().
        model = AutoModelForCausalLM.from_pretrained(
            model_name, quantization_config=quant, device_map={"": 0},
            torch_dtype=torch.float16,
        ).eval()
    else:
        dtype = torch.float16 if device == "cuda" else torch.float32
        _managed_load("rewriter", 3.0, False, get_summary_rewriter.cache_clear)
        model = AutoModelForCausalLM.from_pretrained(
            model_name, torch_dtype=dtype, low_cpu_mem_usage=False
        )
        model = _materialize_to(model, device).eval()
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    for p in model.parameters():
        p.requires_grad_(False)

    _vram.mark_resident("rewriter"); _vram.touch("rewriter")
    _report_loaded("qwen", device)
    return model, tokenizer, device


@lru_cache(maxsize=1)
def get_internvl2():
    """Heavy vision-language model for the C2e rich-description pass.

    Gated behind `settings.heavy_vlm_enabled` so the lighter pipeline
    (Florence-2 + CLIP + Qwen) stays the default. InternVL2-4B fits a
    12 GB consumer GPU in fp16; the 19B variant needs A5000-class.

    Returns (model, tokenizer, device). Raises ImportError if the user
    hasn't enabled the heavy VLM path — callers should catch and skip
    so a missing model gracefully degrades the summary instead of
    breaking it.
    """
    import torch
    from transformers import AutoModel, AutoTokenizer

    from backend.config import settings

    if not settings.heavy_vlm_enabled:
        raise ImportError("heavy_vlm_enabled is False")

    device = get_device()
    model_name = settings.heavy_vlm_model

    dtype = torch.float16 if device == "cuda" else torch.float32
    # `trust_remote_code` because InternVL2 ships its own modeling file
    # (similar pattern to Florence-2). `low_cpu_mem_usage=False` for the
    # same reason: avoid the meta-tensor fast-load that would break
    # `.to(device)`.
    model = AutoModel.from_pretrained(
        model_name,
        torch_dtype=dtype,
        trust_remote_code=True,
        low_cpu_mem_usage=False,
    )
    model = _materialize_to(model, device).eval()
    tokenizer = AutoTokenizer.from_pretrained(
        model_name, trust_remote_code=True
    )

    for p in model.parameters():
        p.requires_grad_(False)

    _report_loaded("internvl2", device)
    return model, tokenizer, device
